### ISSUE TITLE
Install fails with `No available patcher was able to apply patch` error

### ISSUE THREAD

**Issue by gitressa** [phenaproxima/starshot-prototype#100]
The DDEV install process fails with this error:

```
$ git clone https://github.com/phenaproxima/starshot-prototype.git starshot
$ cd starshot && ddev install
[...]
  - Patching drupal/core
      - Found cached patch at /mnt/ddev-global-cache/composer/patches/82926264cd3a329d7424cdcb158156f8e97c2a82e62f91d158d8244f51e706d1.patch
      - Found cached patch at /mnt/ddev-global-cache/composer/patches/1fa48112901bdd460a5c3252c9369259373b4966f60a8574966027db766ce5e5.patch
  - Patching drupal/project_browser
      - Found cached patch at /mnt/ddev-global-cache/composer/patches/124405e87e891dbfdf7236705f4b0fb3190dcb68edc72f5f700cfe3478378e0f.patch

In Patches.php line 288:
  No available patcher was able to apply patch ./patches/project_browser/473-9fb69df1.patch to drupal/project_browser
```

Shouldn't the tests added in #58 (thanks @TravisCarden and @phenaproxima!) have caught this, or are they not yet activated?

## System

OS: Debian 12
```
$ ddev version
 ITEM             VALUE
 DDEV version     v1.23.1
 architecture     amd64
 cgo_enabled      0
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.1
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.1
 docker           26.1.3
 docker-api       1.45
 docker-compose   v2.27.0
 docker-platform  linux-docker
 mutagen          0.17.2
 os               linux
 router           ddev/ddev-traefik-router:v1.23.1
 web              ddev/ddev-webserver:v1.23.1
```

**Comment by gitressa** [comment]
I just tried again, to make sure it wasn't due to a service being down yesterday, but it still happens today.

**Comment by stasadev** [comment]
This repo doesn't have `composer.lock` committed.

That's why it can break over time, as we see here: something changed in https://git.drupalcode.org/project/project_browser and this patch https://github.com/phenaproxima/starshot-prototype/blob/main/patches/project_browser/473-9fb69df1.patch doesn't work anymore, and needs an update.

---

P.S. This should be `test -n "$CI" || ddev launch`, otherwise it only works for macOS:

https://github.com/phenaproxima/starshot-prototype/blob/13972fa33e86dfbbe095b459d765ce4f1ed2d43c/.ddev/commands/host/install#L8

**Comment by phenaproxima** [comment]
Bear in mind this repo is a _prototype_ that's not meant for long-term use...

**Comment by phenaproxima** [comment]
This isn't a DDEV problem, it's that we have an old patch for Project Browser.

As it happens, I can't get the current version of the patch to apply (probably because there are big binary changes involved). The MR (https://www.drupal.org/project/project_browser/issues/3446257) is hopefully going to be merged today anyway -- I'm actively lobbying for it -- and when it does, we won't need the patch. So, rather than keep things broken, I just decided to remove the patch from the prototype and switch to the 2.0.x branch of Project Browser.

**Comment by phenaproxima** [comment]
That would be in cweagans/composer-patches' wheelhouse. :)

**Comment by rfay** [comment]
I would, but that kind of error message has never-ever been reported before this issue. More sane messages have been reported...

Oh, I see, that's new output from composer-patches v2. https://github.com/cweagans/composer-patches/blob/5269693119b245e273db052f12ab23d74aca26fc/src/Plugin/Patches.php#L288

**Comment by gitressa** [comment]
Thanks @phenaproxima, the install works again.
