### ISSUE TITLE
Defunct "Blog" view

### ISSUE THREAD

**Issue by TravisCarden** [phenaproxima/starshot-prototype#105]
There's a "Blog" view at `/blog` that, as far as I can tell, is defunct. If so, let's delete it.

**Comment by phenaproxima** [comment]
Recipes cannot delete anything, but we could disable the view by setting its status to `false`.

**Comment by TravisCarden** [comment]
Then I propose we disable it. It's actually having (what I assume is) an unintended effect in that it's getting detected and inserted into the breadcrumb on blog post nodes, c.f. related https://github.com/phenaproxima/starshot-prototype/issues/133.

**Comment by phenaproxima** [comment]
What if we went the opposite way, and _embraced_ this view, with hackable URLs, for an automatic blog archive functionality?

**Comment by TravisCarden** [comment]
I can get onboard with that, as long as it's not incompatible with the whole goal of recipes being installable on an existing site, such that updating this view would potentially break existing functionality for users who are actually using it.

**Comment by phenaproxima** [comment]
For now, if the `blog` view is on an existing site, it would conflict. This is largely because we don't have config actions for views yet (and creating those will be a bear because views are...complicated, at best).

That said, I don't know if any (or even all) Starshot recipes are idempotent. Worth testing separately, but I'm not sure that should block this, since the prototype is meant as a starting point anyway.

**Comment by TravisCarden** [comment]
True. Seems like a detail that could easily be changed later. I say "go". 🙂

**Comment by phenaproxima** [comment]
Closing based on https://github.com/phenaproxima/starshot-prototype/issues/133#issuecomment-2246783533.
