### ISSUE TITLE
Don't show an "Access denied" error when using `composer run-server`

### ISSUE THREAD

**Issue by TravisCarden** [phenaproxima/starshot-prototype#31]
The `composer run-server` command opens a one-time user reset link each time. After the first time, assuming the user is still logged in, this yields an "Access denied" error. This is a confusing experience, and we should prevent it, if possible.

Note: This is not a function of Starshot itself--it's a long-time quirk of Drupal core. There's an issue to address it that we might use as a jumping off point: [Friendly response to logged-in user landing on user/reset [#3316655]](https://www.drupal.org/project/drupal/issues/3316655).

**Comment by phenaproxima** [comment]
Definitely a very annoying thing that needs to be fixed in core.

That said, the issue you linked was super helpful -- someone already wrote a module for it! I manually tested it, and it worked beautifully. In the name of giving people a better experience, I added it in c1b80c8d22441d6b78e7bf47aad798bc823304da.
