### ISSUE TITLE
[META] Repo management improvements

### ISSUE THREAD

**Issue by AlexSkrypnyk** [phenaproxima/starshot-prototype#62]
With the repo popularity ramping up, I was wondering if there can be improvements done to this repo management:

1. Introduce more meaningful labels
2. Add GHAs to manage labels
3. ~Add contribution information file (at least high-level)~ See https://github.com/phenaproxima/starshot-prototype/issues/65
4. Other

**Comment by phenaproxima** [comment]
I'm very happy to bring in better labels, but since this is just a prototype and is likely to eventually migrate to GitLab (pending governance decisions), I'm not sure it's gonna make a whole lot of difference. But by all means, if you have some label ideas, please mention them here.

What is a "GHA"?

**Comment by AlexSkrypnyk** [comment]
Gha = github actions
