### ISSUE TITLE
Add a recipe for anti-spam / anti-abuse (e.g., ban, captcha, honeypot, etc.)

### ISSUE THREAD

**Issue by effulgentsia** [phenaproxima/starshot-prototype#98]
See https://www.drupal.org/project/ideas/issues/1570102#comment-15610850 for catch's proposal to remove Ban module from Drupal core and replace it with an anti-spam / anit-abuse recipe in Starshot.

**Comment by phenaproxima** [comment]
Right now, all antispam stuff is part of starshot_forms, but I think it would be trivial to refactor that into a new recipe called starshot_antispam, which starshot_forms would build upon. I think a starshot_antispam recipe would be quite useful for the starshot_blog recipe, too, since it enables commenting.
